### ISSUE TITLE
Improve metadata section on the HCA DCP Data Browser

### ISSUE THREAD

**Issue by mshadbolt** [HumanCellAtlas/metadata-schema#1134]
**Description**

 

As the metadata team we want to ensure that the [metadata section](https://data.humancellatlas.org/metadata) of the Data Browser achieves two goals:

1. Enables contributors to understand the metadata we require when accepting data for submission

1. Enables downstream users to understand the metadata we make available for each dataset in the DCP

Currently the Metadata dictionary is not easy to understand, particularly for users that are not familiar with our metadata model. 

This ticket will track ideas and prototypes for improving the section.

**Acceptance Criteria**

 
- [x] A [list](https://docs.google.com/document/d/1Z4M5dq1z0El_qMMgWWwP3QHZF1f2KWnNQMsJNVcwlr4/edit#) of suggestions for improvements that can be implemented
- [ ] Agreement on which suggestions should be implemented
- [ ] A plan for how to implement them in the Data Portal
- [ ] A plan for how we will ensure this section will be kept up-to-date as we update the metadata schema

**Comment by ESapenaVentura** [comment]
Should we create a doc on the Drafts folder and link it here for everyone to share their opinion?

**Comment by diekhans** [comment]
The stalled metadata de-modulation RFC address part of this issue by allowing for type-specific rather than module-specific user-friendly names. 

https://github.com/HumanCellAtlas/dcp-community/tree/rfc-metadata-schema-simplification/rfcs

**Comment by matthewspeir** [comment]
In a recent user interview, they explained that they weren't familiar with the ontologies that we use  (e.g. EFO). It would be great if there was something under the metadata section that explained what ontologies we use (and maybe why we chose them)?

Direct quote:
> The metadata dictionary could be more informative. For example,
> “An ontology term identifier in the form prefix:accession.e.g. "HsapDv:0000087" or "EFO:0002588".”
> This documentation doesn’t describe what the HsapDv or EFO ontologies are. I have never heard of these before; I’m familiar with Gene Ontology but not with these two.

**Comment by mshadbolt** [comment]
@matthewspeir That is great feedback and it is something we hear a lot from researchers as well. The wider scientific community isn't really that familiar with using ontologies to describe parts of their experiment, more at the end for analysis purposes such as gene ontologies. I think it is a great idea to incorporate more info about this into the website.

**Comment by matthewspeir** [comment]
Yeah, the 'why' isn't essential. I think that was more my personal interest rather than the user's interest.

**Comment by lauraclarke** [comment]
Sounds like a page that explains the ontologies we use and a brief rationale might be a great start. I know representatives from other similar consortia frequently ask me that question so having a page I can reference would be great

**Comment by zperova** [comment]
@ESapenaVentura @mshadbolt @lauraclarke I have put the Doc with suggestions that we have discussed in the Metadata/Standards folder - also now linked in the description of this issue.

**Comment by mshadbolt** [comment]
Here's a quick prototype of a metadata browser I put together using R Shiny - https://mshadbolt-hca-ebi.shinyapps.io/metadata_browser/. I think having something interactive, searchable and filterable will allow users to see exactly which fields we collect and the filtering allows them to not be overwhelmed by seeing > 500 fields. It is very beta and more just a proof of concept that can be expanded. I have some placeholders for other things I have been thinking about but no prototypes as yet.

The main use case I am aiming at fulfilling here is for users that want to submit data and want to know:
- which fields are relevant to my experiment
- which fields are required
- whether we have a field that they want to record. e.g. Does the HCA metadata model collect information on smoking history. This can be seen by typing 'smoking' in the search box
- which fields are ontologized. I wanted to be able to specify which ontologies we use for each field but this ended up being harder to derive than I thought.

It is based off the top rows of a spreadsheet and I think that the descriptions can be improved a lot.

**Comment by claymfischer** [comment]
This is fantastic @mshadbolt! Very excited to see how much progress you've already made in this exploration.

**Comment by zperova** [comment]
Improvements to the Metadata Section has been discussed at the Comprehensive Data Portal Content review at the DCP F2F in Boston. Slides form the session are here: https://docs.google.com/presentation/d/1SmqqIoGUjscWDKVNLAwGFN1LBVoTAQhuFyb7WAPwqr0/edit#slide=id.g7062982aed_0_0

@zperova and @matthewspeir will put the summary of the session by November 6 2019.

**Comment by morrisonnorman** [comment]
"@zperova and @matthewspeir will organize and make actionable items from the session on November 6 2019." - Was there any progress on this?

**Comment by matthewspeir** [comment]
@morrisonnorman Yes! Zina, Liz Kiernan, and I met yesterday and sifted through the notes from the session yesterday. We will be making tickets for improvements in the data-portal repo. I believe @zperova has a document of recommendations for the metadata section of the portal.

**Comment by diekhans** [comment]
@zperova would you be so kind as to add a link to your document in this ticket?

**Comment by zperova** [comment]
@diekhans this document summarises what we have discussed prior to the DCP F2F about the metadata section of the Portal and provides what we thought would be the structure of the section: https://docs.google.com/document/d/1SSscSY8OVPNOtQwcr1eHvpYnmwGV5kfzt4EMM7ZvRsc/edit

I am yet to link the specific tasks resulted from the Content Review Session

**Comment by mshadbolt** [comment]
There is now an epic in the Portal Repo where Dave is collecting issues for the metadata revamp
https://app.zenhub.com/workspaces/orange-5d680d7e3eeb5f1bbdf5668f/issues/humancellatlas/data-portal/611

**Comment by ESapenaVentura** [comment]
Closing ticket as this feels done
