### ISSUE TITLE
Plan to prepare content for Metadata and Contribute section of the Data Portal

### ISSUE THREAD

**Issue by zperova** [HumanCellAtlas/metadata-schema#1175]
**Description**

Plan for defining the content for the Metadata section of the Data Portal. For @gabsie to make the mock-pages.

**Acceptance Criteria**

Prepare individual tickets and assign each one:
 
- [x] content for Metadata: Metadata overview - Metadata Standard https://github.com/HumanCellAtlas/metadata-schema/issues/1181 @zperova 
- [x] content for Metadata: Metadata Browser https://github.com/HumanCellAtlas/metadata-schema/issues/1177 and dictionary  https://github.com/HumanCellAtlas/metadata-schema/issues/1179  @mshadbolt 
- [x] content for Contribute: Metadata requirements https://github.com/HumanCellAtlas/metadata-schema/issues/1180 @zperova 
- [x] content for Contribute: How to upload your files https://github.com/HumanCellAtlas/metadata-schema/issues/1180 @zperova 
- [x] content for Contribute: Annotation guide @mshadbolt https://github.com/HumanCellAtlas/metadata-schema/issues/1178
- [x] content for Contribute: Template and examples https://github.com/HumanCellAtlas/metadata-schema/issues/1165 @ESapenaVentura 
- [x] content for Contribute: FAQ https://github.com/HumanCellAtlas/metadata-schema/issues/1182 @zperova
- [x] content for lifecycle of Metadata acquisition https://github.com/HumanCellAtlas/metadata-schema/issues/1183 - TDB

**Comment by zperova** [comment]
Metadata Standard:

The Human Cell Atlas (HCA) is developing a community-driven standard for Single-Cell Biology data. The standard underpins the data life-cycle of the HCA - Data Coordination Platform (HCA-DCP), from contribution and analysis, through to subsequent sharing and reuse.  The vision of the standard is to make the digital research outputs of the Single Cell Biology community  Findable, Accessible, Interoperable and Reusable, according to [FAIR principles](https://www.nature.com/articles/sdata201618).

The motivation behind the development of the Single Cell Standard is to:
- Enable data contributors to describe their project in a way that produces high-quality data that can be maximally exploited by consumers and developers.
- Enable data consumers to interpret data efficiently and in a standardized way.
- Ensure the data collected by the community supports building spatially resolved atlases of cell types and states.
- Support developers who rely on metadata to develop and implement analysis and visualization tools.

**Comment by zperova** [comment]
Metadata fields required/metadata dictionary.

Here you can find a list of user-facing HCA metadata fields with descriptions for required fields: https://docs.google.com/spreadsheets/d/1fZJsN3vpN7vGb9xhRNdj4nrtorJgPXMUXvAS0l5qPZM/edit#gid=828284694

**Comment by zperova** [comment]
@zperova turn into epic split into separate tickets

**Comment by zperova** [comment]
@mshadbolt This is how I envision it to look like when I split into separate tickets.

**Comment by zperova** [comment]
Closing as it has been now split into separate tickets and assigned.
