### ISSUE TITLE
20200331 Release plan - Metadata updates

### ISSUE THREAD

**Issue by zperova** [HumanCellAtlas/metadata-schema#1216]
**Description**

The March release plan has been announced by John (small "r"-release): https://docs.google.com/document/d/1RsD-BjLC2QZZ_ei02FS4OvRljTaySHJBW5ajisXNaU8/edit

According to the plan the Metadata&Wrangler team is responsible for the delivery of the following:

- [x] Study authors clusters/cell type annotation is available (where publicly released). **Deadline: 7 Feb 2020**

- [x] Updated sample and experimental metadata available in form needed by Broad. **Deadline: 7 Feb 2020**

- [x] Get in touch with contributors where cell type annotation are not publically available (Immune Cell Atlas and Dendritic reprogramming, possibly more). **Deadline: 14 Feb 2020**

- [x] Define process for transferring annotation

- [x] Collect all annotations in a form that can be used for remapping (harmonized and ontologized) Deadline: **28 Feb 2020**

- [x] All harmonized annotations are transferred for each dataset. **Deadline: 20 March 2020**

**Acceptance Criteria**

- [x] All of the above is finished

**Comment by lauraclarke** [comment]
@zperova these milestones now need to be adjusted given the change in plan

I think we now need

Collect all annotations in a form that can be used for remapping
 Define process for transferring annotation
Transfer annotation for each dataset

The new plan should be shared with everyone involved in the release and then the overall plan document needs to be updated and the plan should be shared with oversight so they are aware of the change. Kylee's spreadsheet will also need to be updated

**Comment by lauraclarke** [comment]
@mshadbolt @ESapenaVentura and @zperova just to confirm, this ticket isn't closed yet because it merged the metadata updates for loom files which we have done, with the transfer of cell-type annotation which hasn't been done yet.

Is this ticket needed alongside https://github.com/HumanCellAtlas/metadata-schema/issues/1221

**Comment by mshadbolt** [comment]
I believe this is the epic that groups together all tickets related to the r-release.

**Comment by ESapenaVentura** [comment]
I think the purpose of this ticket was to have an epic to link all the sub-tasks for the r-release (loom files updates, cell type annotation) so it will be closed when the r-release tasks are over

**Comment by zperova** [comment]
yes that's an epic that summarises all the tickets that are (or should be if not) mentioned in the body of the issue.

**Comment by lauraclarke** [comment]
@zperova is this finshed?
