### ISSUE TITLE
Facilitate data discovery and standard processing of Human Cell Atlas raw data by provisioning and validating metadata to DCP2. 

### ISSUE THREAD

**Issue by lauraclarke** [HumanCellAtlas/metadata-schema#1266]
# Facilitate data discovery and standard processing of Human Cell Atlas raw data by provisioning and validating metadata to DCP2

The goal of this epic is to establish how the HCA metadata fits into the Terra Data Repository in order to provide sufficient metadata that the standard analysis pipelines can run to produce alignments and transcription quantification and the HCA data browser has the metadata it needs to support discovery and display of all HCA data.

### Key results

The following are the key results for this objective. Each Key result will have its own ticket.

-  [ ] **Key result 1:** A mapping between the HCA metadata entities and attributes and the Terra Core Data Model https://github.com/HumanCellAtlas/metadata-schema/issues/1267
- [x] **Key result 2:** Feedback on the UCSC initial Terra Data Repository HCA data model  https://github.com/HumanCellAtlas/metadata-schema/issues/1268
~**Key result 3:** Schemas for the HCA metadata BigQuery tables in the Terra Data Repo which match the defined HCA TDR data model https://github.com/HumanCellAtlas/metadata-schema/issues/1269~
- [ ] **Key result 4:** Experimental design and cross entity validation rules which ensure data is appropriately groups for processing by the HCA DCP standard analysis pipelines https://github.com/HumanCellAtlas/metadata-schema/issues/1270
- [x] **Key result 5:** An experimental design and cross entity validation tool which can be run before data is exported to DCP2 or SCEA. https://github.com/HumanCellAtlas/metadata-schema/issues/1271

**Comment by lauraclarke** [comment]
As epic editorial seems to be broken linking issues in the main of the ticket

**Comment by ESapenaVentura** [comment]
I think this ticket is outdated @clairerye
