### ISSUE TITLE
Experimental design and cross entity validation rules which ensure data is appropriately grouped for processing by the HCA DCP standard analysis pipelines

### ISSUE THREAD

**Issue by lauraclarke** [HumanCellAtlas/metadata-schema#1270]
# Experimental design and cross entity validation rules which ensure data is appropriately groups for processing by the HCA DCP standard analysis pipelines

The goal of this ticket is to define the rules that will check cross entity relationships and attributes are reported in such a way that provides the standard HCA processing pipelines with the right groups of data and the right attributes for successful operation.

We already know that all data from one scRNA-seq 10x sequencing library needs to be processed together. There may be other expectations that should also be checked.

### Tasks
- [x] Arrange a conversation with the DCP pipelines team to understand what data they process together for their scRNA pipelines and what metadata attributes they rely on

### Acceptance criteria
- [x] List of rules which can be utilized by the https://github.com/ebi-ait/ingest-graph-validator to confirm provided metadata meets the expectations of the analysis pipelines from a cross-entity/experimental design perspective
- [x] Rules are stored and versioned somewhere to ensure we can track changes to rules as the requirements evolve.
- [x] A plan on how to add new rules to this set as new requirements that need this type of validation emerges

**Comment by ESapenaVentura** [comment]
@rays22 and I created a document to collect the rules as we think about them/talk with the analysis team:
https://docs.google.com/document/d/1IjiwDKn7m8h6X3EanpKt5uNcbSdabhpqQhHRy4VRyjo/edit#

@rays22 will be in charge of scheduling a meeting with the pipelines team to ensure we're capturing all the cross-entity validation necessary for them.

**Comment by rays22** [comment]
## Meeting minutes: Cross-validation rules meeting with pipelines team

* uBam unaligned BAMs:
they want to add the cell barcodes to the uBAMs to have all the data in one file
they are happy to share code for fastq -> bam conversion
data must be demultiplexed for pipelines

> If protocol is not 10x or SS2, expect information about reads (What info?)

* barcode length is important to record
* the number of lanes per datasets is important

* if files are demultiplexed -> index file is NOT required


* is the data really coming from the JSON indicated donor organism?

* barnyard experiments: e.g. mouse + human mixture (pipeline is not yet compatible)

* Additional technologies supported in DCP.2
10xV3
(not only single cell, but) single nuclei is supported in DCP2.0 (Enrique: relevant information is here: `library_preparation_protocol.nucleic_acid_source`)
* smartseq2 single end; all smartseq2 is supported

**Comment by lauraclarke** [comment]
> ## Meeting minutes: Cross-validation rules meeting with pipelines team
> * uBam unaligned BAMs:
>   they want to add the cell barcodes to the uBAMs to have all the data in one file
>   they are happy to share code for fastq -> bam conversion
>   data must be demultiplexed for pipelines
> 
We should discuss this, the bam conversion doesn't' sound like something which belongs to ingest

**Comment by lauraclarke** [comment]
Okay based on a question from Kylee, why is there a plan to push uBAMs to DCP? where did that idea come from?

**Comment by ESapenaVentura** [comment]
It may have come from a misunderstanding of something I mentioned. We were talking about the cross entity rules and 10x experiments came up, and I talked about how we're pushing uBam to the archives for 10x experiments with index files.

Apologies if this was misinterpreted, I was just mentioning it and I commented that I don't have a clear vision of the flow archives/ingest -> TDR

**Comment by lauraclarke** [comment]
Thanks for the clarification. If they can take uBAMs then it does make our lives slightly less complex but certainly, we shouldn't say they have to in the first instance

For the two datasets that we pushed to the ENA do we still have the fastq files?

**Comment by ESapenaVentura** [comment]
For Peng He and Elisa Laurenti's datasets, we have the fastq files in their respective backup folders (Same area as in the tickets, but changing the preffix to `hca-wrangler-backup`)

**Comment by ESapenaVentura** [comment]
>- List of rules which can be utilized by the https://github.com/ebi-ait/ingest-graph-validator to confirm provided metadata meets the expectations of the analysis pipelines from a cross-entity/experimental design perspective

**List of rules**

- If a protocol is paired-end, expect at least 2 files per set
- If it’s 10x, expect at least 2 files per set (Based on what we've been told, we have to modify one of the already implemented rules, as we have a rule set up to expect 3-4 files for 10x)
- If protocol is not 10x or SS2, expect following information about reads:
    - Single-end, paired-end
    - Barcode location (within files) 
    - Barcode/read offset (UMI and cell barcode)
    - Barcode/read length (UMI and cell barcode)
    - Barcode file, read file indicated
- The same file is not linked to 2 different sets
- If more than one R1/R2/I1/I2 in a set, ensure lane index is specified
- A sequencing and library preparation protocol is linked to the files
- Confirm that information from the donor is linked correctly (This one isn't too clear and we couldn't come up with a defined requirement in the meeting)

>- Rules are stored and versioned somewhere to ensure we can track changes to rules as the requirements evolve.

Rules will be stored in the [Ingest graph validator](https://github.com/ebi-ait/ingest-graph-validator) repo under the folder `graph_test_set` in the form of adoc documents. 

>- A plan on how to add new rules to this set as new requirements that need this type of validation emerges

There is a template in the ingest graph validator repository but I will create a `Readme.md` under the `graph_test_set` folder indicating how to add new rules and test them, as well as links to the readme in the proper documentation in the metadata-schema/data-wrangling repos.

**Comment by ESapenaVentura** [comment]
About the last point:
>A plan on how to add new rules to this set as new requirements that need this type of validation emerges

The PR on the [ingest-graph-validator]() repo has a template and instructions on how to add new tests. A couple things of the process need to be refined but as an MVP it's ready to go!

Once the PR is merged I will proceed to close the ticket if @rays22 is ok with it.

**Comment by lauraclarke** [comment]
@rays22 what do you need to do so this ticket can be closed?

If any new work as emerged, please create as tickets associated with https://github.com/ebi-ait/hca-ebi-wrangler-central/

**Comment by rays22** [comment]
@lauraclarke We still need to merge the different github branches with the new cypher validation code into the master branch or a appropriate fork.
We can add that remaining task to issue [Add new rules for cross-entity validation which ensure data is appropriately grouped for processing by the HCA DCP standard analysis pipelines #3](https://github.com/ebi-ait/ingest-graph-validator/issues/3), so I think we can close this issue.

**Comment by rays22** [comment]
Complete.
