### ISSUE TITLE
Ensure ingest-graph-validator tool can be used to validate experimental design before (meta)data is exported to DCP2 or SCEA

### ISSUE THREAD

**Issue by lauraclarke** [HumanCellAtlas/metadata-schema#1271]
# An experimental design and cross entity validation tool which can be run before data is exported to DCP2 or SCEA.

The goal of this ticket is to ensure the rules defined to ensure metadata provides the required information on how data is grouped and individual attributes for the analysis pipelines 

This work should build on the existing tool provided by https://github.com/ebi-ait/ingest-graph-validator rather than starting from scratch

### Acceptance criteria
- [x] Gather requirements from Ingest to enable integration into Ingest
- [x] Metadata submissions can be validated by wranglers with respect to rules defined in https://github.com/HumanCellAtlas/metadata-schema/issues/1270 before submission to the DSP/DCP/SCEA
- [x] A plan exists to finish the integration of this tool with the main ingest validation flow when spreadsheets are uploaded to the DCP interface
- [x] The tool can be pointed at a new rule set

**Comment by zperova** [comment]
This requires to collect requirements from Ingest to enable integration into Ingest

**Comment by ESapenaVentura** [comment]
Just tested the graph validator. I can assure:

- Can feed from data in the DCP by a submission UUID
- Can run tests on data based on cypher queries

The detailed instructions are in the [repo](https://github.com/ebi-ait/ingest-graph-validator), but to test this:

```
ingest-graph-validator init
ingest-graph-validator hydrate ingest <ingest_uuid>
ingest-graph-validator action test <path_to_tests>
```

Questions I will research today/tomorrow:
- Does it use the old DCP1 ingest API or the archiver API? (As this might affect ingestion of non-DCP data)
- Where can we integrate this step in the data ingestion? (Prior to actually integrating this tool into ingest)
- How can we improve the tests output? Currently, it just gives a pass/fail without an explanation of the error.

**Comment by ESapenaVentura** [comment]
>  Does it use the old DCP1 ingest API or the archiver API? (As this might affect ingestion of non-DCP data)

Yes it does. An alternative ingest API url can be passed as an environmental variable, but I would have to investigate how to do that. Alternatively, it can be changed manually in the code, but I don't think that's a good option.

**Comment by ESapenaVentura** [comment]
> How can we improve the tests output? Currently, it just gives a pass/fail without an explanation of the error.

Ticket on the ingest-graph-validator repository [here](https://github.com/ebi-ait/ingest-graph-validator/issues/1)

**Comment by ESapenaVentura** [comment]
I have talked with Rolando about integration of the ingest-graph-validator tool into ingest to test datasets, and the key points from the conversation are:
- Depending on the aim, it could take from half sprint to 1 sprint of dedicated dev work to integrate the tool into ingest
- In order to facilitate the work, before the end of sprint we should come with a list of milestones/user-features (Small but with value) that will lead up to `complete integration into ingest`

I will be in charge of creating the document and collect the milestones/user-features, making sure they are presented as a "ladder" rather than as a flat list. Once this is done, it will be passed to the devs (Probably through @clairerye ?) and Justin/Claire will be the ones deciding on the prioritisation.

In the meantime, while this tool is integrated, I will work on a readme tutorial on how to use it so wranglers can test datasets manually in the next dataset iteration.

**Comment by ESapenaVentura** [comment]
A plan for integration of the tool has been shared. 

I am waiting on feedback but should be finished before the start of the next sprint.

Document [here](https://docs.google.com/document/d/1mqTKTUo4VjjMygnZpJZ4uzADFDc0tKDNhWVpQVNvi-Y/edit#heading=h.463cazvds5b9)

**Comment by ESapenaVentura** [comment]
The plan exists and it's [here](https://docs.google.com/document/d/1mqTKTUo4VjjMygnZpJZ4uzADFDc0tKDNhWVpQVNvi-Y/edit?ts=5eb42114#). Has been circulated and I'm currently gathering the last opinions before passing it onto @clairerye and @justincc for prioritisation.

I will close the ticket now as there is no more work to be done on this assignment.

As a note to previous comments, there is a PR in place that has added the tests and documentation on how to test datasets.
