### ISSUE TITLE
Schema minor and major updates for adhering to Schema Style Guide

### ISSUE THREAD

**Issue by malloryfreeberg** [HumanCellAtlas/metadata-schema#691]
### If you open an issue to address an item(s), link the issue to the Epic. Check off the item when the change is released (in integration).

**Description**

 

As a consumer of the HCA metadata schemas, I would like to be sure that the metadata standards follow a set of consistent formatting and rules.

**Acceptance Criteria**

### Type:Biomaterial
- [x] cell_line.json
    - [x] change `cell_line_type` to **type?** (maybe need a better word than "type") (remove redundancy - "cell_line" - in field name) 
- [x] cell_suspension.json
    - [x] change `total_estimated_cells` to `estimated_cell_count` because the field takes a single value and so should not be a plural term (#649)
    - [x] change `selected_cell_type` to `selected_cell_types` because the field is an array (#923)
    - [x] change description for `selected_cell_type` to clarify that this is a predicted or enriched-for cell type and might not actually be the "real" cell type based on gene expression (slightly changes the semantic meaning of the field) (#923)
- [x] donor_organism.json
    - [x] change `familial_relationship` to `familial_relationships` since the field takes an array (#768 )
- [x] organoid.json
    - [x] change model_for_organ to model_organ to remove extra word ("for") and be consistent with related term model_organ_part
    - [x] change organoid_age to age to remove redundant word ("organoid")
    - [x] change organoid_age_unit to age_unit to remove redundant word ("organoid")
    - [x] change organoid_size to size to remove redundant word ("organoid")
    - [x] change organoid_size_unit to size_unit to remove redundant word ("organoid")
    - [x] change organoid_morphology to morphology to remove redundant word ("organoid")
    - [x] change organoid_growth_environment to growth_environment to remove redundant word ("organoid")
    - [x] change organoid_stored_oxygen_levels to stored_oxygen_levels to remove redundant word ("organoid")
    - [x] change `organoid_type ` to `type` (actually to something else that is more descriptive than "type") to remove redundant word ("organoid") (#736)

### Type:File

- [x] sequence_file.json (#805)
    - [x] change `insdc_run` to `insdc_run_accessions` because the field is an array

### Type:Project

- [x] project.json (#324)
    - [x] change `insdc_project` to `insdc_project_accessions` and make the field an array
    - [x] change `geo_series ` to `geo_series_accessions` and make the field an array
    - [x] change `array_express_investigation ` to `array_express_accessions` and make the field an array
    - [x] change `insdc_study ` to `insdc_study_accessions` and make the field an array

### Type:Protocol

- [x] analysis_protocol.json (#931)
    - [x] change `protocol_type` to `type` (actually to something else that is more descriptive than "type") to remove redundant word ("protocol")
- [x] aggregate_generation_protocol.json (#746 )
    - [x] change `aggregate_formation_method` to `formation_method` to remove redundancy ("aggregate")
    - [x] change `aggregate_cell_uniformity ` to `cell_uniformity` to remove redundancy ("aggregate")
- [x] collection_protocol.json
    - [x] change `collection_method` to `method` to remove redundancy ("collection")
    - [x] change `protocol_reagents` to `reagents` to remove redundancy ("protocol")
- [x] differentiation_protocol.json (#924)
    - [x] change `differentiation_method` to `method`  to remove redundancy ("differentiation")
    - [x] change `small_molecules` to an array because the field take more than one value
- [x] dissociation_protocol.json
    - [x] change `dissociation_method ` to `method`  to remove redundancy ("dissociation")
    - [x] change `protocol_reagents` to `reagents` to remove redundancy ("protocol")
- [x] enrichment_protocol.json (#925)
    - [x] change `enrichment_method ` to `method`  to remove redundancy ("enrichment")
    - [x] change `min_size_selected` to `minimum_size`
    - [x] change `max_size_selected` to `maximum_size`
- [x] ipsc_induction_protocol.json (#926)
    - [x] remove `ipsc_induction_produced_in_house` field to remove redundancy (`process.location`) (#459)
    - [x] change `ipsc_induction_method ` to `method` to remove redundancy ("ipsc_induction")
    - [x] change `ipsc_induction_factors` to `factors` to remove redundancy ("ipsc_induction") **Should this be an array field since it can accept more than 1 value?**
    - [x] **Are `ipsc_induction_kit` and `protocol_reagents` redundant?** If so, remove `ipsc_induction_kit` and change `protocol_reagents` to `reagents` to remove redundancy ("ipsc_induction")
- [x] imaging_preparation_protocol.json
    - [x] **create new ticket**
- [x] imaging_protocol.json
    - [x] **create new ticket**
- [x] library_preparation_protocol.json
    - [x] change `library_construction_approach` to `library_construction_method` to be consistent with all other protocol schemas using the term "method"
- [x] sequencing_protocol.json
    - [x] change `sequencing_approach` to `method` to be consistent with other protocol schemas using the term "method" and to remove redundancy ("sequencing")
- [x] protocol.json (#931)
    - [x] change `protocol_type` to `type` to remove redundancy ("protocol")

### Type:Process

- [x] process.json (#931)
    - [x] change `process_type ` to `type` to remove redundancy ("process")
- [x] analysis_process.json (#931)
    - [x] change `process_type ` to `type` to remove redundancy ("process")

### Module:Biomaterial
- [x] state_of_specimen.json (#792)
    - [x] change `gross_image` to `gross_images` since field is an array
    - [x] change `microscopic_image` to `microscopic_images` since field is an array
- [x] timecourse.json (#745)
    - [x] change `timecourse_value` to `value` to remove redundancy ("timecourse")
    - [x] change `timecourse_unit` to `unit` to remove redundancy ("timecourse")
    - [x] change `timecourse_relevance` to `relevance` to remove redundancy ("timecourse")

### Module:Process

- [x] insdc_experiment.json
    - [x] change `insdc_experiment` to `insdc_experiment_accession`
- [x] plate_based_sequencing.json
    - [x] change `cell_quality` to `well_quality` because the field is really asking about the quality of the well

### Module:Project

- [x] contact.json (#927)
    - [x] change `contact_name` to `name` to remove redundant word (contact)
- [x] funder.json (#542)
    - [x] change `funder_name` to `organization` to remove redundant word (funder)
- [x] publication.json (#928)
    - [x] change `publication_title` to `title` to remove redundancy
    - [x] change `publication_url` to `url` to remove redundancy

### Core:Biomaterial

(#929)
- [x] change `biosd_biomaterial` to `biosample_accession` to be more precise about what the field is
- [x] change `insdc_biomaterial` to `insdc_sample_accession` to be more precise about what the field is

### Core:File

(#375 )
- [x] change `file_format` to `format` to remove redundancy ("file") 

### Core:Process

(#930)
- [x] change `process_location` to `location` to remove redundancy ("process")
- [x] change `operator` to `operators` to reflect that this field is an array

**Comment by malloryfreeberg** [comment]
Removed remaining issues linked to this Epic that are currently in the Icebox, as these issues aren't being considered at this time.

At this time, all linked issues are at least pre-released (merged into develop).

**Comment by samanehsan** [comment]
The change `change dissociation_method to method to remove redundancy ("dissociation")` does not have a link so I assume it's in the icebox, but just wanted to note it will affect the secondary analysis subscriptions

**Comment by malloryfreeberg** [comment]
@samanehsan we did put the `dissociation_method` -> `method` one through: https://github.com/HumanCellAtlas/metadata-schema/pull/808 

Apologies for the confusion in the issue. We weren't great about putting a link next to each change.

**Comment by samanehsan** [comment]
Oh okay! Thanks for the clarification 🙂 We will need to update this field in our queries!
