### ISSUE TITLE
Schema patch updates for adhering to Schema Style Guide - Imaging

### ISSUE THREAD

**Issue by zperova** [HumanCellAtlas/metadata-schema#714]
## If you open an issue to address any items here, please check them off the list in the Epic and link the issue to the Epic.
Description

As a consumer of the HCA metadata schemas, I would like to be sure that the metadata standards follow a set of consistent formatting and rules.

Acceptance Criteria

# Type

## Type: Protocol

- [x] image_file.json
    - [x] add user_friendly to `file_core`
- [x] target.json
  - [x] move second sentence from description to guidelines in `molecule_name`
  - [x] move second sentence from description to guidelines in `molecule_id`
  - [x] expand `reagent_name`
- [x] imaging_preparation_protocol.json
  - [x] user_friendly is missing from property `protocol_core`
  - [x] fix description in `fresh_slicing_method`
  - [x] fix description in `final_slicing_method`
  - [x] add example in `pre_final_slice_preservation_method`
  - [x] update description for `expansion marker`
- [x] imaging_protocol.json
    - [x] add user-friendly term to `protocol_core`
    - [x] move "including manufacturer and model information about the stand, camera and objective." from description to guidelines for `microscope_setup_description`
    - [x] separate examples with semi colons
    - [x] move "Must be a child term..." from `microscopy_technique` description to guidelines
    - [x] add example to `immersion_medium_type`
    - [x] change to US spelling of nanometers and micrometeres
    - [x] remove "(scaling factor)" from description
    - [x] add example to `tile_size_y`
    - [x] add example to `tile_size_x`
    - [x] change example for `overlapping_tiles` to "Should be one of: yes, or no."
    - [x] change description for `overlapping_tile` to "Whether tiles were collected with overlap."

**Comment by malloryfreeberg** [comment]
@zperova looks like all these changes were made and merged to develop. Feel free to close this Epic!
