### ISSUE TITLE
Type and scope of most id fields is not defined in the schema

### ISSUE THREAD

**Issue by diekhans** [HumanCellAtlas/metadata-schema#733]
**Type and scope of most id fields is not defined in the schema**

The format or scope of most id fields is not in the description.  How to define ids fields is not described in the style guide.

This came up in #732, where library_prep_id is described as  "A unique ID for the library preparation.", however, it is in only unique to a submitter.

**Comment by malloryfreeberg** [comment]
I think we can address the scope and type of IDs in the `guidelines` attribute for those fields. We should make a list of all the "id" fields (there aren't that many outside of the IDs in the *_core schemas), and make sure they have appropriate scoping information in the guidelines.

**Comment by malloryfreeberg** [comment]
### Proposal
#### For Biomaterial, Process, and Protocol types
- Change `*_id` to `*_label` (or `*_alias`) --> project-wide unique, supplied by contributor
- Remove `*_name`
- Keep `*_description`
#### For all types
- Change `provenance.document_id` to `provenance.guid` --> DS-wide unique, supplied by DCP (ingest)
- [optional] Move `provenance.guid` to top level of type (so just `guid`)

**Comment by malloryfreeberg** [comment]
Other "id" fields:
- `funder.grant_id`
- ``
- ``
- ``

**Comment by hewgreen** [comment]
The primary keys should have a consistent regex that can be easily found with code. This allows entities to be linked together. When updating the spreadsheet builder function the fact that the sequencing file primary key was 'file name' and other entities were all 'biomaterial id' was annoying and hard coding was required to catch this exception. The programatic name should be consistent but the user friendly name could be anything.

channel.channel_id and target.channel_id should definitely be brought in line with other primary keys even though they will be nested. Sub arrays that will be represented in separate tabs should ideally have primary keys. For imaging users will need these keys to reference probe, channel and codeword (which is a list of channels).

**Comment by malloryfreeberg** [comment]
Ok, so we need suggestions for changing the following fields:

#### Maybe
- [ ] `funder.grant_id` --> ? (We can keep the u-f name "Grant ID" since this is what most people refer to this value as, but what should the programmatic name be?)
- [ ] `target.molecule_id` --> `probes.target_molecule_label`  (#813)

#### Definitely
- [ ] `plate_based_sequencing.plate_id` --> `plate_based_sequencing.plate_label`
- [ ] `plate_based_sequencing.well_id` --> `plate_based_sequencing.well_label`
- [ ] `sequence_file.library_prep_id` --> _Might not need if we introduce new Library Preparation entity_
- [ ] `channel.channel_id` --> `channel.channel_label` (#813)
- [ ] `target.channel_id` --> `probes.channel_label`  (#813)

**Comment by malloryfreeberg** [comment]
@tburdett this thread has some thoughts/suggestions on renaming 'id' fields.

**Comment by malloryfreeberg** [comment]
> ### Proposal
> #### For Biomaterial, Process, and Protocol types (in *_core modules)
> * [ ]  Change `*_id` to `label` (or `alias`) --> project-wide unique, supplied by contributor
> * [ ]  Remove `*_name` fields
> * [ ]  Change `*_description` to `description`
> 
> #### For all types
> * [ ]  Change `provenance.document_id` to `provenance.guid` --> DS-wide unique, supplied by DCP (ingest)
> * [ ]  [optional] Move `provenance.guid` to top level of type (so just `guid`)
> 
> #### Other fields - maybe change
> * [ ]  `funder.grant_id` --> ? (We can keep the u-f name "Grant ID" since this is what most people refer to this value as, but what should the programmatic name be?)
> * [x]  `target.molecule_id` --> `probes.target_molecule_label`  (#813)
> 
> #### Other fields - definitely change
> * [x]  `plate_based_sequencing.plate_id` --> `plate_based_sequencing.plate_label` (#837)
> * [x]  `plate_based_sequencing.well_id` --> `plate_based_sequencing.well_label` (#837)
> * [ ]  `sequence_file.library_prep_id` --> _Might not need if we introduce new Library Preparation entity_
> * [x]  `channel.channel_id` --> `channel.channel_label` (#813)
> * [x]  `target.channel_id` --> `probes.channel_label`  (#813)

@simonjupp let me know if this looks good. If so, I'll move it to the style guide epic.

**Comment by rolando-ebi** [comment]
I’d go with "alias" instead of "label", "label" is synonymous with “tag” and when I think of tags I think of many tags per thing.
