### ISSUE TITLE
Add remaining schema Style Guide checks to schema linter

### ISSUE THREAD

**Issue by malloryfreeberg** [HumanCellAtlas/metadata-schema#890]
**Description**

 

As a metadata team member (committer) who makes changes to the metadata schemas, I would like to be sure my schema changes adhere to the Style Guide by running the schema linter.

Features are from this [doc](https://docs.google.com/document/d/1pg-YCBE9YGAEVVZQN6p3nKMghdjiUSd8i4mlnRheoUs/edit#).

**Acceptance Criteria**

 
The following checks should be added to the linter:
 
- [x] Every schema title should be sentence-case (first char is uppercase letter, no underscores).
- [x] Every field that references another schema using $ref must point to a valid schema.
- [x] For every field that has a pattern attribute, the pattern must be a valid regular expression.
- [x] Example values for fields with a pattern must match the regular expression.
- [x] ~For every field that is of type array, the field name should be plural.~ not worth the effort to implement right now
- [x] Fields must be allowed to have `oneOf` as a property.

Ontology-specific checks to be added to the linter:

- [x] Each ontology schema must have text, ontology, and ontology_label fields
- [x] Every ontology field must have a graph_restriction attribute that is an object
- [x] Every graph_restriction must have an ontologies attribute
    - [x] ~Must be valid curies~ Moved to issue https://github.com/HumanCellAtlas/metadata-schema/issues/1012
    - [x] ~Check that each listed ontology is present in HCA OLS instance~ Moved to issue https://github.com/HumanCellAtlas/metadata-schema/issues/1012
- [x] Every graph_restriction must have a classes attribute
    - [x] ~Must be valid curies~ Moved to issue https://github.com/HumanCellAtlas/metadata-schema/issues/1012
    - [x] ~Check that each listed class is present in HCA OLS instance~ Moved to issue https://github.com/HumanCellAtlas/metadata-schema/issues/1012
- [x] Every graph_restriction must have a relations attribute
    - [x] Relation attribute is a list that must minimally be ["rdfs:subClassOf"]
- [x] Every graph_restriction must have a direct attribute
    - [x] Must be false
- [x] Every graph_restriction must have a include_self attribute
    - [x] Must be true or false

**Comment by malloryfreeberg** [comment]
@daniwelter what should be checked for under "Must be valid curies" for the ontologies and classes attributes? I don't know exactly what I should be coding to do this check. If it involves doing some ontology lookup, I might punt to a new GH issue that I'll make for the "Check that each listed class is present in HCA OLS instance" points.

**Comment by daniwelter** [comment]
I'm happy to take the ontology section and implement the OLS lookups. I'm pretty sure I have code for that sitting around somewhere that I can recycle.

**Comment by malloryfreeberg** [comment]
Cool. Let me finish up what I can here, and then I can hand off to you? We can merge what I've done so far now to get some of the pesky messages taken care of. Then make a new ticket for the ontology work. I'm just about done with the rest of the things here.

**Comment by malloryfreeberg** [comment]
@daniwelter I moved ontology-related checks to issue https://github.com/HumanCellAtlas/metadata-schema/issues/1012
